//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class CommonIcon {
  static const String _family = 'iconfont';
  
  CommonIcon._();
  
  static const IconData dianti = IconData(0xe637, fontFamily: _family); // 电梯
  static const IconData tianranqi = IconData(0xe639, fontFamily: _family); // 天然气
  static const IconData yigui = IconData(0xe636, fontFamily: _family); // 衣柜
  static const IconData gengduo = IconData(0xe61e, fontFamily: _family); // 更多
  static const IconData chuang = IconData(0xe623, fontFamily: _family); // 床
  static const IconData tingchechang = IconData(0xe624, fontFamily: _family); // 停车场
  static const IconData shuzhuo = IconData(0xe625, fontFamily: _family); // 书桌
  static const IconData zhinengmensuo = IconData(0xe626, fontFamily: _family); // 智能门锁
  static const IconData kuandai = IconData(0xe627, fontFamily: _family); // 宽带
  static const IconData shuba = IconData(0xe628, fontFamily: _family); // 书吧
  static const IconData xiyifang = IconData(0xe629, fontFamily: _family); // 洗衣房
  static const IconData dianshiji = IconData(0xe62a, fontFamily: _family); // 电视机
  static const IconData weibolu = IconData(0xe62b, fontFamily: _family); // 微波炉
  static const IconData diancilu = IconData(0xe62c, fontFamily: _family); // 电磁炉
  static const IconData reshuiqi = IconData(0xe62d, fontFamily: _family); // 热水器
  static const IconData anquanjiankong = IconData(0xe62e, fontFamily: _family); // 安全监控
  static const IconData chugui = IconData(0xe62f, fontFamily: _family); // 橱柜
  static const IconData chouyouyanji = IconData(0xe630, fontFamily: _family); // 抽油烟机
  static const IconData kongtiao = IconData(0xe631, fontFamily: _family); // 空调
  static const IconData nuanqi = IconData(0xe632, fontFamily: _family); // 暖气
  static const IconData shafa = IconData(0xe633, fontFamily: _family); // 沙发
  static const IconData bingxiang = IconData(0xe634, fontFamily: _family); // 冰箱
  static const IconData xiyiji = IconData(0xe635, fontFamily: _family); // 洗衣机
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class CommonIconPreview extends StatelessWidget {
  const CommonIconPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(CommonIcon.dianti, "dianti", "电梯"),
    _PreviewIcon(CommonIcon.tianranqi, "tianranqi", "天然气"),
    _PreviewIcon(CommonIcon.yigui, "yigui", "衣柜"),
    _PreviewIcon(CommonIcon.gengduo, "gengduo", "更多"),
    _PreviewIcon(CommonIcon.chuang, "chuang", "床"),
    _PreviewIcon(CommonIcon.tingchechang, "tingchechang", "停车场"),
    _PreviewIcon(CommonIcon.shuzhuo, "shuzhuo", "书桌"),
    _PreviewIcon(CommonIcon.zhinengmensuo, "zhinengmensuo", "智能门锁"),
    _PreviewIcon(CommonIcon.kuandai, "kuandai", "宽带"),
    _PreviewIcon(CommonIcon.shuba, "shuba", "书吧"),
    _PreviewIcon(CommonIcon.xiyifang, "xiyifang", "洗衣房"),
    _PreviewIcon(CommonIcon.dianshiji, "dianshiji", "电视机"),
    _PreviewIcon(CommonIcon.weibolu, "weibolu", "微波炉"),
    _PreviewIcon(CommonIcon.diancilu, "diancilu", "电磁炉"),
    _PreviewIcon(CommonIcon.reshuiqi, "reshuiqi", "热水器"),
    _PreviewIcon(CommonIcon.anquanjiankong, "anquanjiankong", "安全监控"),
    _PreviewIcon(CommonIcon.chugui, "chugui", "橱柜"),
    _PreviewIcon(CommonIcon.chouyouyanji, "chouyouyanji", "抽油烟机"),
    _PreviewIcon(CommonIcon.kongtiao, "kongtiao", "空调"),
    _PreviewIcon(CommonIcon.nuanqi, "nuanqi", "暖气"),
    _PreviewIcon(CommonIcon.shafa, "shafa", "沙发"),
    _PreviewIcon(CommonIcon.bingxiang, "bingxiang", "冰箱"),
    _PreviewIcon(CommonIcon.xiyiji, "xiyiji", "洗衣机"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('CommonIcon'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
